### ISSUE TITLE
Deviations from the standard layout

### ISSUE THREAD

**Issue by LucianU** [rdegges/django-skel#28]
Is there any reason why the wsgi.py file isn't inside project as it is in a standard Django project? Also, why is there a requirements.txt file besides the reqs directory? Are these Heroku specific?

**Comment by rdegges** [comment]
Hi there!

The wsgi.py file isn't included as django-skel is opinionated for deployment / etc. The preferred webserver to deploy django-skel projects with is gunicorn, which can run things fine without any wsgi.py file (which is why it isn't included).

The requirements.txt file is a standard python convention in web apps. Basically, you throw all your production requirements in there (in this case, it simply includes the reqs/prod.txt requirements), that way new users wanting to install all production stuff can simply run 'pip install -r requirements.txt' at the top-level to have everything work.

Heroku also uses the top-level requirements.txt file, but that's really for standards.

Hope that helps explain!

**Comment by LucianU** [comment]
I don't know what you mean by requirements.txt being a standard python convention in web apps. I know that every Python package should have one if it has dependencies outside of the standard library, but that's it. From my point of view, having the reqs directory is enough in this case, because you can specify the path.

**Comment by rdegges** [comment]
So, the convention for python libraries (reusable stuff) is to put all dependencies in your setup.py script--this way when you download stuff from PyPI it'll automatically install all your dependencies nicely.

For web apps, the tradition is to put all your requirements to run the web app inside a top-level file named `requirements.txt`. Since django-skel provides different requirements files (one for development-specific stuff, one for testing, one for production), I tried to stay true to the standard by the top-level file continue to exist, but just pull in the production requirements.

**Comment by LucianU** [comment]
Ok, I haven't heard of this standard for Python web apps and I think it's weird that it exists. I don't see the reason why you need to have the requirements at the root of the packages in a single file, especially since in the case of web apps it's common to have different deployment environments and, as such, different files for each environment.
