### ISSUE TITLE
Amazon S3 and STATIC_URL

### ISSUE THREAD

**Issue by hoorzad** [rdegges/django-skel#31]
Hi,

I'm a newbie. Sorry if my question is too obvious.

If calling format is set to subdomain, shouldn't static url be something like this:

```
STATIC_URL = "https://%s.s3.amazonaws.com/static/" % AWS_STORAGE_BUCKET_NAME
```

Also, why isn't MEDIA_URL defined?

**Comment by rdegges** [comment]
It's actually been a little while since I've looked at this--but if you try it out the way it is, you'll see that it works. I can't remember exactly why though.

Also: MEDIA_URL has a default value (provided by Django). MEDIA_URL is used to point to user-uploaded content. Since many projects don't require user-uploaded content, and django-skel is meant to work with 'just the basics', we don't include anything for that.
