### ISSUE TITLE
What about django 1.5.1?

### ISSUE THREAD

**Issue by chimeno** [rdegges/django-skel#33]
I am just wondering if there are compatibility issues with django 1.5.1.

**Comment by andrewaustin** [comment]
Currently, you have to make some changes to get things to play nicely with Django 1.5. The fixes are pretty simple, and the error messages that Django gives you basically tells you how to fix the issue. Off the top of my head you have to:
1. Add something additional to the log handlers
2. Change some import paths because they've been moved
3. Whitelist the domain/subdomain you're using one of the newer django settings
4. I believe there are two other warnings that python manage.py runserver will give you that explains what you need to change

I've been meaning to submit some pull requests to fix the issues, will try to get to it tomorrow.

**Comment by blanchardjeremy** [comment]
Same question, but what about Django 1.6? Any plans to upgrade this?

**Comment by rdegges** [comment]
Yes! I'm actually just looking into this now.

**Comment by cottrellio** [comment]
+1 for 1.6 (maybe even 1.7 as it should be released soon) :) Great work btw!!! Love this skeleton!

**Comment by locomo** [comment]
+1 for 1.7

**Comment by aladagemre** [comment]
I have an extended fork of this repo. These two commits should do the job I think:

https://github.com/aladagemre/django-skel/commit/26bbdeb8713bb5a81bc9d386408235f60e0b01aa
https://github.com/aladagemre/django-skel/commit/fcf253b2b274683b185ddc50cc8ab2a49272d9d4

(except you will remove django-allauth which is my extra package)

**Comment by pydanny** [comment]
Closed on account of #64
